// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC76XPCsvJpX-axaCJDwapFby73CxcElzI',
    appId: '1:107130246683:web:f4cbba217e25b0ab708abe',
    messagingSenderId: '107130246683',
    projectId: 'gochitchat-90be8',
    authDomain: 'gochitchat-90be8.firebaseapp.com',
    storageBucket: 'gochitchat-90be8.appspot.com',
    measurementId: 'G-H8J3KMSRMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmQhDBUjFJUEuFADPkxzy_em0aAsIJtRg',
    appId: '1:107130246683:android:67722a5eeb411770708abe',
    messagingSenderId: '107130246683',
    projectId: 'gochitchat-90be8',
    storageBucket: 'gochitchat-90be8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQnX1jPW7oOVbO9OBEkZWVZfvszjxjzy4',
    appId: '1:107130246683:ios:f2d913bd21d88934708abe',
    messagingSenderId: '107130246683',
    projectId: 'gochitchat-90be8',
    storageBucket: 'gochitchat-90be8.appspot.com',
    iosBundleId: 'com.example.goChitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQnX1jPW7oOVbO9OBEkZWVZfvszjxjzy4',
    appId: '1:107130246683:ios:caeddeb02d8de374708abe',
    messagingSenderId: '107130246683',
    projectId: 'gochitchat-90be8',
    storageBucket: 'gochitchat-90be8.appspot.com',
    iosBundleId: 'com.example.goChitChat.RunnerTests',
  );
}
